title:            ASR for sociolinguists
author:           Joe Pearce
description: >
  A tutorial for using ASR to aid you in sociolinguistic and phonetic research.

version:          1.0
gitbook_version:  3.2.3

url:              '"https://praat-enthusiast.github.io/"'
baseurl:          '/asr'
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
