remote-theme: sighingnow/jekyll-gitbook
title: ASR for sociolinguists
baseurl: "/asr"
toc:
    enabled: true
    h_min: 1
    h_max: 3
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
